################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_SRCS := 
S_UPPER_SRCS := 
ASM_SRCS := 
REL_SRCS := 
C_DEPS := 
RELS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
tools/z80/hex2bin/src \
tools/wpcapslip \
tools \
tools/stm32w/wpcapslip6 \
tools/stm32w/uip6_bridge \
tools/stm32w/uip6_bridge/dev \
tools/stm32w \
tools/sky/uip6-bridge \
tools/sky/uip6-bridge/dev \
tools/sky \
tools/sensinode/nano_usb_programmer \
tools/sensinode/nano_programmer/windows \
tools/sensinode/nano_programmer \
tools/sensinode/nano_programmer/linux \
tools/release-tools/compile-platforms \
tools/cooja/examples/project_new_interface \
tools/cooja/config \
tools/cooja/build \
tools/cooja/build/obj_cooja \
platform/z1sp/dev \
platform/z1sp \
platform/z1 \
platform/z1/dev \
platform/z1/apps \
platform/wismote \
platform/wismote/dev \
platform/win32/loader \
platform/win32/ctk \
platform/win32 \
platform/win32/cfs \
platform/stm32test \
platform/stk501 \
platform/stk500 \
platform/stepper-robot/usb-msc \
platform/stepper-robot \
platform/stepper-robot/stepper \
platform/stepper-robot/gateway \
platform/sky \
platform/sky/dev \
platform/sky/apps \
platform/sentilla-usb \
platform/sensinode \
platform/sensinode/dev \
platform/sensinode/apps/batmon \
platform/redbee-econotag/dev \
platform/redbee-econotag \
platform/redbee-dev \
platform/pc-6001/loader \
platform/pc-6001/dev \
platform/pc-6001/ctk \
platform/pc-6001 \
platform/pc-6001/apps/webserver-mini \
platform/pc-6001/apps/tinysample \
platform/pc-6001/apps/multithread \
platform/native/dev \
platform/native \
platform/msb430 \
platform/msb430/dev \
platform/msb430/apps \
platform/minimal-net \
platform/micaz \
platform/micaz/dev \
platform/micaz/dev/sensors \
platform/micaz/apps/mts310 \
platform/micaz/apps \
platform/mbxxx/dev \
platform/mbxxx \
platform/mbxxx/apps \
platform/mb851/dev \
platform/mb851 \
platform/mb851/apps \
platform/jcreate \
platform/jcreate/dev \
platform/iris \
platform/iris/dev \
platform/iris/dev/sensors \
platform/iris/apps/mts310 \
platform/iris/apps \
platform/exp5438 \
platform/esb \
platform/esb/net \
platform/esb/dev \
platform/esb/apps \
platform/cooja/testapps \
platform/cooja/sys \
platform/cooja \
platform/cooja/net \
platform/cooja/lib \
platform/cooja/dev \
platform/cooja/cfs \
platform/cc2530dk \
platform/cc2530dk/dev \
platform/c64/lib \
platform/c64 \
platform/c64/cfs \
platform/c128/lib \
platform/c128 \
platform/c128/cfs \
platform/avr-zigbit \
platform/avr-rcb \
platform/avr-ravenusb \
platform/avr-ravenlcd \
platform/avr-raven \
platform/avr-raven/apps/raven-webserver \
platform/avr-raven/apps/raven-lcd-interface \
platform/avr-raven/apps/raven-ipso \
platform/avr-atmega128rfa1 \
platform/avr-atmega128rfa1/apps/raven-webserver \
platform/avr-atmega128rfa1/apps/raven-lcd-interface \
platform/avr-atmega128rfa1/apps/raven-ipso \
platform/atari/lib \
platform/atari \
platform/apple2enh/sys \
platform/apple2enh/lib \
platform/apple2enh \
examples/z1sp \
examples/z1/tutorials \
examples/z1 \
examples/z1/rssi_scanner \
examples/z1/ipv6/z1-websense \
examples/wget \
examples/webserver-ipv6-raven \
examples/webserver-ipv6 \
examples/webserver \
examples/webbrowser \
examples/udp-stream \
examples/udp-ipv6 \
examples/test-ipv6 \
examples/telnet-server \
examples/sky-shell-webserver \
examples/sky-shell-exec \
examples/sky-shell \
examples/sky-ip \
examples/sky \
examples/servreg-hack \
examples/sensinode/udp-ipv6 \
examples/sensinode \
examples/sensinode/sniffer \
examples/sensinode/serial-flash \
examples/sensinode/sensors-ipv6 \
examples/sensinode/sensors \
examples/sensinode/event-post \
examples/sensinode/energy-scan \
examples/sensinode/disco \
examples/sensinode/cc2431-location-engine \
examples/sensinode/border-router \
examples/rime \
examples/rest-example \
examples/ravenusbstick \
examples/powertrace \
examples/ping-ipv6 \
examples/new-ipv6 \
examples/netperf \
examples/multi-threading \
examples/mb851/webserver-ajax \
examples/mb851/udp-ipv6-sleep \
examples/mb851/temperature \
examples/mb851/telnet-server \
examples/mb851/shell-exec \
examples/mb851/mb851-websense \
examples/mb851/mb851-shell \
examples/mb851/coffee-test \
examples/mb851/button \
examples/mb851/acc-sensor \
examples/jcreate \
examples/irc \
examples/ipv6/slip-radio \
examples/ipv6/sky-websense \
examples/ipv6/simple-udp-rpl \
examples/ipv6/rpl-udp \
examples/ipv6/rpl-collect \
examples/ipv6/rpl-border-router \
examples/ipv6/native-border-router \
examples/ipso-ipv6-raven \
examples/hello-world \
examples/ftp \
examples/example-shell \
examples/esb \
examples/er-rest-example \
examples/email \
examples/collect \
examples/cc2530dk/udp-ipv6 \
examples/cc2530dk \
examples/cc2530dk/sniffer \
examples/cc2530dk/border-router \
examples/antelope/shell \
examples/antelope/netdb \
doc \
cpu/z80 \
cpu/z80/loader \
cpu/z80/lib \
cpu/z80/dev \
cpu/x86 \
cpu/stm32w108 \
cpu/stm32w108/small_printf \
cpu/stm32w108/hal/micro/cortexm3 \
cpu/stm32w108/hal/micro/cortexm3/stm32w108 \
cpu/stm32w108/e_stdio/src \
cpu/stm32w108/dev \
cpu/native \
cpu/native/net \
cpu/msp430 \
cpu/msp430/f5xxx \
cpu/msp430/f2xxx \
cpu/msp430/f1xxx \
cpu/msp430/dev \
cpu/mc1322x \
cpu/mc1322x/tools/ftditools \
cpu/mc1322x/tests \
cpu/mc1322x/src \
cpu/mc1322x/lib \
cpu/cc253x \
cpu/cc253x/dev \
cpu/cc2430 \
cpu/cc2430/dev \
cpu/avr \
cpu/avr/radio/rf230bb \
cpu/avr/radio/rf230 \
cpu/avr/radio/mac \
cpu/avr/radio/ieee-manager \
cpu/avr/dev/usb \
cpu/avr/dev/usb/storage \
cpu/avr/dev/usb/serial \
cpu/avr/dev/usb/rndis \
cpu/avr/dev \
cpu/arm/stm32f103 \
cpu/arm/common/usb \
cpu/arm/common/usb/msc \
cpu/arm/common/usb/cdc-eth \
cpu/arm/common/usb/cdc-acm \
cpu/arm/common/dbg-io \
cpu/arm/common/SD-card \
cpu/arm/at91sam7s \
cpu/arm/at91sam7s/loader \
cpu/6502/sys \
cpu/6502/net \
cpu/6502/lib \
cpu/6502/dhcp \
cpu/6502/ctk \
core/sys \
core/net \
core/net/rpl \
core/net/rime \
core/net/mac \
core/loader \
core/lib \
core/dev \
core/ctk \
core/cfs \
apps/webserver-nano \
apps/webserver \
apps/webbrowser \
apps/vnc \
apps/unit-test \
apps/twitter \
apps/telnetd \
apps/telnet \
apps/slip-cmd \
apps/shell \
apps/servreg-hack \
apps/serial-shell \
apps/rest-http \
apps/rest-common \
apps/rest-coap \
apps/program-handler \
apps/process-list \
apps/powertrace \
apps/ping6 \
apps/netconf \
apps/irc \
apps/ftp \
apps/erbium \
apps/er-coap-07 \
apps/er-coap-03 \
apps/email \
apps/directory \
apps/dhcp \
apps/deluge \
apps/collect-view \
apps/codeprop \
apps/cmdd \
apps/calc \
apps/antelope \
apps/about \

